// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/dont-trust-verify': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../runtime/middleware/context').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../runtime/handlers/api/dont-trust-verify/index.get').default>>>>
    }
    '/api/dont-trust-verify/challenge': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../runtime/handlers/api/dont-trust-verify/challenge.post').default>>>>
    }
    '/api/dont-trust-verify/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../runtime/handlers/api/dont-trust-verify/register.post').default>>>>
    }
    '/api/dont-trust-verify/match': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../runtime/handlers/api/dont-trust-verify/match.post').default>>>>
    }
  }
}
export {}