// Users, stores, apps (POS/crowdfund), API keys, payment methods (LN/onchain), wallet, rates, email
// All routes are guarded by requireAdmin (x-btcpay-admin-secret header)
export const adminEndpointDefs = [
  { method: 'GET', route: 'admin/server/info', file: 'admin/server-info.get.js' },
  { method: 'POST', route: 'admin/users', file: 'admin/users.post.js' },
  { method: 'GET', route: 'admin/users', file: 'admin/users.get.js' },
  { method: 'GET', route: 'admin/users/:userId', file: 'admin/user.get.js' },
  { method: 'POST', route: 'admin/users/:userId/lock', file: 'admin/user-lock.post.js' },
  { method: 'DELETE', route: 'admin/users/:userId', file: 'admin/user.delete.js' },
  { method: 'POST', route: 'admin/users/:userId/api-keys', file: 'admin/user-api-keys.post.js' },
  { method: 'GET', route: 'admin/stores', file: 'admin/stores.get.js' },
  { method: 'POST', route: 'admin/stores', file: 'admin/stores.post.js' },
  { method: 'GET', route: 'admin/stores/:storeId', file: 'admin/store.get.js' },
  { method: 'PUT', route: 'admin/stores/:storeId', file: 'admin/store.put.js' },
  { method: 'DELETE', route: 'admin/stores/:storeId', file: 'admin/store.delete.js' },
  { method: 'GET', route: 'admin/stores/:storeId/users', file: 'admin/store-users.get.js' },
  { method: 'POST', route: 'admin/stores/:storeId/users', file: 'admin/store-users.post.js' },
  { method: 'DELETE', route: 'admin/stores/:storeId/users/:userId', file: 'admin/store-user.delete.js' },
  { method: 'GET', route: 'admin/stores/:storeId/apps', file: 'admin/store-apps.get.js' },
  { method: 'GET', route: 'admin/apps', file: 'admin/apps.get.js' },
  { method: 'GET', route: 'admin/apps/:appId', file: 'admin/app.get.js' },
  { method: 'DELETE', route: 'admin/apps/:appId', file: 'admin/app.delete.js' },
  { method: 'POST', route: 'admin/stores/:storeId/apps/pos', file: 'admin/app-pos.post.js' },
  { method: 'PUT', route: 'admin/apps/pos/:appId', file: 'admin/app-pos.put.js' },
  { method: 'GET', route: 'admin/apps/pos/:appId', file: 'admin/app-pos.get.js' },
  { method: 'GET', route: 'admin/apps/crowdfund/:appId', file: 'admin/app-crowdfund.get.js' },
  { method: 'PUT', route: 'admin/apps/crowdfund/:appId', file: 'admin/app-crowdfund.put.js' },
  { method: 'GET', route: 'admin/stores/:storeId/payment-methods/lightning', file: 'admin/ln.get.js' },
  { method: 'PUT', route: 'admin/stores/:storeId/payment-methods/lightning', file: 'admin/ln.put.js' },
  { method: 'DELETE', route: 'admin/stores/:storeId/payment-methods/lightning', file: 'admin/ln.delete.js' },
  { method: 'GET', route: 'admin/stores/:storeId/payment-methods/onchain', file: 'admin/onchain.get.js' },
  { method: 'GET', route: 'admin/stores/:storeId/payment-methods/onchain/btc', file: 'admin/onchain-btc.get.js' },
  { method: 'PUT', route: 'admin/stores/:storeId/payment-methods/onchain/btc', file: 'admin/onchain-btc.put.js' },
  { method: 'DELETE', route: 'admin/stores/:storeId/payment-methods/onchain/btc', file: 'admin/onchain-btc.delete.js' },
  { method: 'POST', route: 'admin/stores/:storeId/payment-methods/onchain/btc/preview', file: 'admin/onchain-preview.post.js' },
  { method: 'POST', route: 'admin/stores/:storeId/payment-methods/onchain/btc/generate', file: 'admin/onchain-generate.post.js' },
  { method: 'GET', route: 'admin/stores/:storeId/wallet', file: 'admin/wallet.get.js' },
  { method: 'GET', route: 'admin/stores/:storeId/wallet/utxos', file: 'admin/wallet-utxos.get.js' },
  { method: 'GET', route: 'admin/stores/:storeId/wallet/objects', file: 'admin/wallet-objects.get.js' },
  { method: 'GET', route: 'admin/stores/:storeId/wallet/transactions', file: 'admin/wallet-transactions.get.js' },
  { method: 'GET', route: 'admin/stores/:storeId/payment-methods', file: 'admin/store-payment-methods.get.js' },
  { method: 'GET', route: 'admin/rate-sources', file: 'admin/rate-sources.get.js' },
  { method: 'GET', route: 'admin/stores/:storeId/rates/configuration', file: 'admin/rate-source.get.js' },
  { method: 'PUT', route: 'admin/stores/:storeId/rates/configuration', file: 'admin/rate-source.put.js' },
  { method: 'GET', route: 'admin/stores/:storeId/rates', file: 'admin/rates.get.js' },
  { method: 'GET', route: 'admin/stores/:storeId/rates/currency/:currency', file: 'admin/rate-preview.get.js' },
  { method: 'POST', route: 'admin/stores/:storeId/email/send', file: 'admin/email.post.js' }
]
